name: Hello World

on:
  workflow_dispatch:

jobs:
  say-hello-inline-bash:
     runs-on: ubuntu-latest
     steps:
       - run: echo "Hello worlds"

  say-hello-inline-python:
     runs-on: ubuntu-latest
     steps:
       - name: Print hello work py
         shell: python
         run: |
           print("Hello world from python")

  more-complex-bash-script:
      runs-on: ubuntu-latest
      steps:
        - name: More complex bash script
          shell: bash
          run: |
            export fname="John"
            export lname="Doe"
            echo "${fname} ${lname}"
            
          
        
